- ci/pipeline.yml
modified:   pipeline.yml
- Added grype config to pipeline.yml
- 
- 
There are no security considerations for this request
> Added a line for grype config

- ci/pipeline.yml
modified:   pipeline.yml
- Added a resource type for s3-simple in pipeline.yml
- 
- 
There are no Security considerations for this request
> Added a resource type for s3-simple

- ci/scan-container.sh
modified:   scan-container.sh
- Modified the grype config script in scan-container.sh
- 
- 
There are no security considerations
> Modified grype config script

- ci/pipeline.yml
modified:   pipeline.yml
- Modified the grype config pipeline entry in pipeline.yml
- 
- 
There are no security considerations for this request
> Modified grype config pipeline entry

- ci/conmon-scan-ecr-container.sh
modified:   ci/conmon-scan-ecr-container.sh
- Added grype config to the ECR scanning pipeline for conmom.
- 
- 
There are no security considerations for this request.
> Added gype config to the ECR scanning pipeline

- ci/pipeline.yml
modified:   ci/pipeline.yml
- Modified grype ignore config inputs
modified:   ci/pipeline.yml
- 
- 
There are no security considerations for this request.
> Modified grype ignore config inputs

- ci/pipeline.yml
modified:   ci/pipeline.yml
- Added grype ignore config to the tag task 
- modified:   ci/pipeline.yml
- 
- 
There are no security considerations for this request.
> Added grype ignore config to the tag task

- ci/pipeline.yml
- Updates the pipeline to use the main branch
None
> Update pipeline source

- ci/audit-ecr-container.sh
- Use usg audit instead of cis-audit as required for newer ubuntu image
None
> Update audit script to work with newer ubuntu

- ci/conmon-scan-ecr-container.yml
- ci/cve-check.yml
- ci/delete-image.yml
- ci/ecr-cve-check.yml
- ci/list-images.yml
- ci/pipeline.yml
- ci/scan-container.yml
- ci/scan-ecr-container-no-ignore.yml
- ci/scan-ecr-container.yml
- Update scripts so that they use the harden-concourse-task container
Using hardened containers makes our system more secure
> Update scripts to used hardened containers

- ci/pipeline.yml
- Switch branch back to main now that testing is done
None
> Switch branch back to main

- terraform/ecr.tf
- Add hardened container ecr repos through terraform instead of manually
None
> Add ecr repos

- ci/audit-ecr-container.yml
- ci/conmon-scan-ecr-container.yml
- ci/cve-check.sh
- ci/cve-check.yml
- ci/delete-image.yml
- ci/ecr-cve-check.sh
- ci/ecr-cve-check.yml
- ci/list-images.sh
- ci/list-images.yml
- ci/pipeline.yml
- ci/scan-container.sh
- ci/scan-container.yml
- ci/scan-ecr-container-no-ignore.yml
- ci/scan-ecr-container.sh
- ci/scan-ecr-container.yml
- terraform/terraform-apply.yml
- Update pipeline triggers
- Update scripts to use image tag
- Update output format for scripts
None
> Update pipelines and use image tag with containers

- ci/ecr-cve-check.sh
- ci/pipeline.yml
- Update notification messages to make clear that CVEs need to be reviewed
None
> Update notification messages

- terraform/pages-ecr.tf
- Add's Pages ECR TF
- Add's `pages-build-container` repository
Allow Pages team to manage their ECR repositories separately
> feat: Add Pages ECR repositories to TF

- terraform/ecr.tf
- Pages terraform is being added to a separate stack and branch
- Revert #29 
- Revert #30
None
> Revert Pages Terraform changes

- ci/pipeline.yml
- Update pipeline branch to main
-
-
None
> Update pipeline branch to main

- ci/audit-ecr-container.yml
- ci/pipeline.yml
- Fix audit script to set correct tag for each image
None
> Set up audit script to use correct tag for image

- ci/pipeline.yml
- Adds jobs for latest scans on hardened images to see scan results more quickly
- Sorts the pipeline to make it look nicer
None, this is just a quality of life improvement
> Adds jobs for latest scans and makes the pipeline look nicer

- ci/pipeline.yml
- Fixed regression from a merge for staging env
-
-
all good 
None
> fixed merge regression

- ci/pipeline.yml
- Updates job and resource naming conventions for clarity
- Removing unnecessary resources
None, this just aims to make the pipeline more readable
> Fix naming

- .gitignore
- docs/harden-pipelines.md
- See title.
- Related to epic: https://github.com/cloud-gov/product/issues/1723
None.
> Add instructions for using hardened images in pipelines

- README.md
- Add blank line so that new gpg key is detected
None
> adding blank line

- README.md
- Removes extra line for gpg update
None
> remove line

- ci/audit-ecr-container.sh
- ci/audit-ecr-container.yml
- Update comment in script with space and add empty line at end of file to force update
None
> update comment in script
