ci/conmon-scan-ecr-container.sh
ci/pipeline.yml
ci/scan-container.sh
ci/scan-ecr-container.sh

modified:   ci/pipeline.yml
modified:   ci/conmon-scan-ecr-container.sh
modified:   ci/scan-container.sh
modified:   ci/scan-ecr-container.sh
- Added the grype ignore config to all scanning jobs in ci/pipeline.yml
- Modified the grype configuration to point to the grype.yaml file during the scanning task.
- 
There are no security considerations related to this request.

Added the grype ignore config to all scanning jobs

---

ci/conmon-scan-ecr-container.sh
ci/pipeline.yml
terraform/terraform-apply.yml

- Fix pipelines so that conmon jobs don't trigger on ignore file update
- Fix conmon scan script 'cp -r' warning that shows up in ci
- Update terraform job to use hardened container
Hardened containers are more secure

update pipeline triggers, fix container reference, fix cp warning

---

terraform/ecr.tf

Since Pages uses mutable image tags, updated repository images untag their older iterations so this adds an ECR lifecycle policy to clean up the untagged images.
- Remove untagged images after 7 days
None

feat: Pages repo add 7 day untagged image expiration

---

ci/pipeline.yml

- Removes unneeded jobs
- Updates naming conventions to remove deprecation warnings
- Update conocurse-task and s3-resource conmon scans to be done on hardened images
- Set yaml anchors properly   
Running the conmon scans against our hardened images is important for compliance purposes

Pipeline cleanup

---

ci/pipeline.yml

- Changes audit scripts to use latest image
Allows us to audit our latest image

Update audit scripts to scan latest image

---

ci/ecr-cve-check.sh
ci/pipeline.yml

- This removes duplicate CVEs and speeds up the check script
- Adds past due CVEs to their own arrays so they can be used for future work
None, just performance improvement

Remove duplicates

---

ci/conmon-scan-ecr-container.sh
ci/conmon-scan-ecr-container.yml
ci/grype.yaml
ci/pipeline.yml
ci/scan-container.sh
ci/scan-container.yml
ci/scan-ecr-container.sh
ci/scan-ecr-container.yml

- Adds grype ignore file to repo and updates pipeline to use that file instead of the file in s3
None, any CVEs listed in the ignore file should be ones that are false positives or don't actually affect us

Update pipeline to use grype ignore file in repo instead of s3

---

ci/pipeline.yml
terraform/ecr.tf
terraform/terraform-apply.yml

- Added audit and scan tasks for staging versions of both the concourse and s3 images
- There is no logging or actual code changes, this is strictly adding images for staging to prep for gating into the prod environment
This increases security as we are adding checks for images before they are deployed to production

Create staging env

---

ci/delete-image.sh
ci/ecr-cve-check.sh
ci/pipeline.yml

- This adds gating on CVEs from staging to production
- Creates job to upload image to production, and adds conditional code to only run this job if passing CVE and Audit checks
- Removes Audit jobs for production images, since we should only need to Audit staging images
- Fixes some naming conventions
- Fixes delete script
- Are log statements using a logging library with a logging level set? Setting a logging level means that log statements "below" that level will not be written to the output. For example, if the logging level is set to `INFO` and debugging statements are written with `log.debug` or similar, then they won't be written to the otput, which can prevent unintentional leaks of …

CVE gating

---

ci/conmon-scan-ecr-container.sh
ci/pipeline.yml
templates/conmon_csv.tmpl

- Adds template to be used by grype for conmon scan
None, updates the grype output to be easier to work with

update conmon scan to use template file and output as csv

---

ci/audit-ecr-container.yml
ci/conmon-scan-ecr-container.yml
ci/cve-check.yml
ci/delete-image.yml
ci/ecr-cve-check.yml
ci/list-images.yml
ci/pipeline.yml
ci/scan-container.yml
ci/scan-ecr-container-no-ignore.yml
ci/scan-ecr-container.yml

- Updates pipeline so that instead of specifying a specific tag it will always grab the latest image
Using the latest container will keep us up to date with security fixes

Use latest container

---

ci/audit-ecr-container.sh

- Save xml report and html report to the same directory so that they may be deleted easily in the future.
Deletion of these files will be necessary when we are running the audit before creating the image. Since we are currently running the audit after the image is created, it is not saved to the image. I will be …

set xml report output to same directory as html report

---

ci/pipeline.yml

- Also sends notifications to slack on audit success/failure
Helps meet container scanning requirements by alerting us when we have successful or failed audits of our images.

add slack notifications for audit jobs

---

ci/pipeline.yml

- Adds `do` step to on_success and on-failure so that we can run email and slack steps
None, just fixing the pipeline

add do step to success and fail steps so that they run multiple puts

---

ci/audit-ecr-container.sh

- This creates a blank cis-audit.xml file in advance to avoid errors writing to the file, like what's done for the .html file
None, fixes an error writing to the audit.xml file

create blank xml file in advanced to avoid errors writing to the file

---

ci/audit-ecr-container.sh

- specify PWD so that the result files can be written to correctly
None, fixing errors

use PWD so that usg can write the result files correctly

---

ci/audit-ecr-container.yml
ci/conmon-scan-ecr-container.yml
ci/cve-check.yml
ci/delete-image.yml
ci/ecr-cve-check.yml
ci/list-images.yml
ci/pipeline.yml
ci/scan-container.yml
ci/scan-ecr-container-no-ignore.yml
ci/scan-ecr-container.yml
terraform/terraform-apply.yml

- Updates pipeline so that individual task files no longer have to reference the harden-concourse-task resource, and makes it easier by having to update only the pipeline file rather than all the task files
None, just a QoL improvement

Use pipeline image

---

ci/pipeline.yml

- Fixes conmon scan jobs to reference csv file rather than xml
-
-
None, just fixing file type

Fix conmon scans

---

terraform/ecr.tf

- Split to lines and order alphabetically
- I created another repository manually in the console, which I shouldn't have done. I'll do another PR to see if we can make Terraform adopt it.
None. Expanding existing pattern of use.

Add two new repositories and make list easier to scan

---

terraform/ecr.tf

- Because resources are named by index, terraform interpreted the reordering as a renaming and tried to destroy/recreate most repositories
- This PR reverts the order for now; will follow up to try to rename the resources to use the repository names to allow order independence
None. Refactor.

Restore original order, since resources are named by index

---

terraform/ecr.tf

- See title and previous commit
None

Fix the order of image repositories -- missed git-resource last time

---

terraform/ecr.tf

- See https://developer.hashicorp.com/terraform/language/meta-arguments/for_each#basic-syntax
- Thanks to @markdboyd 
None

Attempt switching to for_each for order independent resource creation

---

terraform/ecr.tf

- See title
None, adds new ECR repo

Create ecr repo for slack-notification-resource

---

ci/pipeline.yml
terraform/ecr.tf

- Change image tag mutability
- Set tags to empty block to remove null value error
- Change pipeline so that terraform apply doesn't automatically trigger. This way we can confirm the changes before applying
Improves security by making sure we check the terraform changes before applying them

Update ecr terraform

---

terraform/ecr.tf

- See title
- @dandersonsw this will fix the error in the push step of the pipeline. (It's not a friendly error)
None.

Add new repository for general-task image

---

terraform/ecr.tf

-Adding the s3-resource repo to ecr.tf.
-
-
There are no security considerations for this change.

Adding the s3-resource repo to ecr.tf.

---

terraform/ecr.tf

- Added the semver-resource repo.
-
-
There are no security considerations for this change.

Added the semver-resource.

---

ci/conmon-scan-ecr-container.sh
ci/pipeline.yml

- Restore XML-formatted reports, which are required by our ConMon processing team
- Reviewer discussion: https://groups.google.com/a/gsa.gov/g/cloud-gov-compliance/c/OhxaJrJPcwM
- Team discussion: https://gsa-tts.slack.com/archives/C04UFEJF413/p1693508451785299
None.

ConMon requires XML-formatted reports but HTML is more human-readable

---

terraform/ecr.tf

- Create a repo in ECR for the email-resource image
None, just creates a repo for our hardened email-resource image

Add email-resource to terraform

---

terraform/ecr.tf

- Adds cron-resource repo to ECR
Creates an ECR repo for our hardened cron-resource

Adds cron-resource

---

terraform/ecr.tf

- Add time resource to list of repos to be created by terraform
Adds an ECR repo for the time-resource image

Add time resource

---

terraform/ecr.tf

- Set tags_all to empty brackets so that plugin doesn't error on null value
None, just a pipeline fix

Set tags_all

---

terraform/ecr.tf

- Create repo in ECR for our hardened cf-cli-resource image
Creates a new repo in ECR for our hardened image

add cf-cli-resource

---

ci/pipeline.yml
terraform/ecr.tf

- Removed references to oracle dependency that is no longer in use.
-
-
Improves security by removing unused dependencies

Remove oracle

---

ci/pipeline.yml

- Remove pipeline-tasks resource as it is no longer used in any jobs
Removing unused items

remove unused pipeline-tasks resource
